asset_path: /root/autodl-tmp/lerobot/target/wooden_target.stl
usd_dir: /root/autodl-tmp/lerobot/simulation/leisaac_wood_pick/source/leisaac_wood_pick/leisaac_wood_pick/assets
usd_file_name: wooden_target.usd
force_usd_conversion: true
make_instanceable: false
mass_props:
  mass: 0.03
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexHullCollisionAPI
  hull_vertex_limit: null
  min_thickness: null
translation: !!python/tuple
- -0.00575
- -0.00575
- -0.04
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 0.001
- 0.001
- 0.001
##
# Generated by MeshConverter on 2026-08-06 at 22:23:55.
##
